### ISSUE TITLE
No text found in svg

### ISSUE THREAD

**Issue by Krib89** [Don-Chris/Plot2LaTeX#3]
Hey Chris,

thanks for the great work and the constant fixing of the issues! Your last update definetly fixed the error I'd got! Unfortunately, for Matlab 2023a, I am back at the problem with Plot2Latex not finding any elements while restoring the text in the svg file. For Matlab 2020b everything is fine! :)
The warning says: Plot2LaTeX.m: No text elements found and updated. Please check if no text is used or if the Renderer is "painters" and if there are any characters present that can't be correctly printed to text.

Thanks for everything and have a great weekend!

**Comment by Don-Chris** [comment]
Hey @Krib89,
Could you send a script with an example figure that results in the warning you mentioned? This would help in fixing the issue.
I tried my test figures in matlab online, but couldn't recreate the error.

**Comment by Krib89** [comment]
Hi @Don-Chris 

sorry for the late response, but i needed to do some troubleshooting myself, because I was not able to replicate the error reliably. I figured out, that using the 'CMU Serif' font in the plots causes the error. CMU Serif is the font used in Latex. I am not sure, if this is fixable since i know that Matlab has some problems handling fonts. What do you think?

Best regards!

**Comment by Don-Chris** [comment]
@Krib89 Can you explain to me, why you would change the font of the text manually? I use the option 'Interpreter'='latex' to change the font to the latex font type. The problem can't really be fixed from Plot2LaTeX's point of view since matlab can't correctly export the figure if it has the wrong fontName. I could add a check if the fontName is right in all text elements but that would add an extra conversion time of 10-20%.

**Comment by Krib89** [comment]
Hi @Don-Chris it is a relic from my phd thesis. Before I used Plot2Latex, I tried other ways to export my figues. You don't have to add the check for me! Maybe just a note in the readme helps other people :) 
Thanks for all your work!
Best regards

**Comment by Don-Chris** [comment]
Done :)
